apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: deployments-applicationset
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/ryanaslett/omf-argocd-applications.git
        revision: main
        directories:
          - path: deployments/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/ryanaslett/omf-argocd-applications.git
        targetRevision: main
        path: '{{path}}'
        helm:
          valueFiles:
            - values.yaml
          parameters: []
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
