apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: deployments-applicationset
  namespace: argocd
spec:
  generators:
    - git:
        #TODO: rename this to omf-argocd.git
        repoURL: https://github.com/OvertureMaps/omf-superset-argocd.git
        revision: main
        directories:
          - path: argocd-applications/deployments/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        #TODO: rename this to omf-argocd.git
        repoURL: https://github.com/OvertureMaps/omf-superset-argocd.git
        targetRevision: main
        path: '{{path}}'
        helm:
          valueFiles:
            - values.yaml
          parameters: []
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
